### PR TITLE
Save Hubbard V values for ci tests

### PR DESCRIPTION
**Pull request by gsavva**
In this PR, the V values are printed to the yaml file to be used in the verification (ci) tests.
The yaml file now looks like the following:
```
atom001-Fe :
  U:    4.610377
atom002-O  :
  U:    8.234760
atom003-O  :
  U:    8.234760
Fe-3d-Fe-3d:
  001-001:    4.610377
Fe-3d-O-2p:
  001-036:    0.149231
Fe-3d-O-2p:
  001-005:    0.149231
Fe-3d-O-2p:
  001-003:    0.149231
```
The U values are written first and then the V values, those that native QE writes in `HUBBARD.dat` (the 6  nearest neighbors of every atom).
But `HUBBARD.dat` file does not contain the U values for all atoms, which is the reason for keeping the 1st part of the yaml.
However, some U values appear twice.

### CODE REVIEW

**Comment by gsavva** [comment]
When keys are repeated (in a yaml file), only the last key is retained when read as dictionaries in python. This is because dictionaries cannot have duplicate keys.
So the yaml schema above is not correct.
The following is fine though:
```
Fe-001-O-005:
  3d-2p:    0.149231
Fe-001-O-003:
  3d-2p:    0.149231
```

**Comment by toxa81** [comment]
Another option to consider is this:
```
Fe-3d-Fe-3d:
  001-001:    4.610377
Fe-3d-O-2p:
  001-036:    0.149231
  001-005:    0.149231
  001-003:    0.149231
```
But I like your version as well. Maybe the same notation for atoms should be applied to local part, like this
```
Fe-001:
  U:    4.610377
```

**Comment by gsavva** [comment]
It would be better to use what you suggested @toxa81 
```
Fe-3d-O-2p:
  001-036:    0.149231
  001-005:    0.149231
  001-003:    0.149231
```
However, that would require to check if the atoms and orbitals are the same from a previous entry (loop) and write under an existing entry in the yaml. Given the loop structure in QE, I would avoid complicating the code to keep track of what atom-orbital has already been written, hence the schema I proposed.
I've already done the necessary change, I'll commit them shortly and see how this behaves in ci tests.

**Comment by toxa81** [comment]
And the diff python script automagically works because the structure of the new yaml file is the same as it was before, right?

**Comment by gsavva** [comment]
Indeed, the diff script works without modifications because the structure of the additional V values is the same as the existing U values (whose label is slightly modified).
**OLD yaml**
```
atom0001:
  U:    7.1011
atom0003:
  U:    9.2287
```
**NEW yaml**
```
atom001-Ni1:
  U:    7.1011
atom003-O  :
  U:    9.2287
Ni1-001-O-047:
  3d-2p:    0.3529
Ni1-001-O-023:
  3d-2p:    0.3529
```

**Review by toxa81 — APPROVED** [review]
LGTM

**Pull request merged**
