### PR TITLE
nlcglib and other changes

### PR DESCRIPTION
**Pull request by simonpintarelli**
- add new nlcg api
- add an optional `DIRECT_MINIZATION` namelist to input file (if present nlcglib is enabled)
- enable sirius automatically (as preferred by THEOS group), for vanilla QE  `-use_qe_scf` flag was added)
- don't call `post_init_PAW` which deallocates the PAW arrays, they are picked up later when calling `reset_gvectors` in https://github.com/electronic-structure/q-e-sirius/blob/nlcg-qe72/PW/src/run_pwscf.f90#L303, which calls `init_run` -> `setup_sirius`, where the PAW arrays are accessed again
- add a .fortls for fortran language server / set `.editorconfig` to use 2 spaces for indent

### CODE REVIEW

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
@simonpintarelli the ci/cd works and reports issues

**Comment by toxa81** [comment]
@simonpintarelli  ci/cd works and reports issues

**Comment by simonpintarelli** [comment]
Thanks for the help. Sorry, I was confused first by fortran line break. Now I see I corrupted electrons.f90 during rebase, let me clean it.

**Review by toxa81 — APPROVED** [review]
LGTM!

**Pull request merged**
