### PR TITLE
[refactor] nscf in sirius

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
Hi @gcistaro 
you need to modify nscf logic in the following way: you need to setup a new ground state obect out of new k-point set object and execute the nscf by sirius. 
1) new k-point set handler must be declared and new k-point set must be created for the list of k-points that you extracted from the code:
CALL sirius_create_kset(sctx, num_kpoints, kpoints, wkpoints, .FALSE., ks_handler1)
2) new ground state handler must be created and creaetd from the new k-point set:
 CALL sirius_create_ground_state(ks_handler1, gs_handler1)
3)  put_density_to_sirius() function must be changed to work with the given ground state; then you will be able to put density from QE to the new ground state object:
    CALL put_density_to_sirius(gs_handler1)
4) put_density_matrix_to_sirius() function must be changed to work with the given ground state
 IF (okpaw) THEN
      CALL put_density_matrix_to_sirius(gs_handler1)
      CALL sirius_generate_density(gs_handler1, paw_only=.TRUE.)
    ENDIF
5) then you can generate the effective potential 
    CALL sirius_generate_effective_potential(gs_handler1)
6) and then initialize k-point set and solve for the KS wave-functions
 CALL sirius_initialize_subspace(gs_handler, ks_handler)
    CALL sirius_find_eigen_states(gs_handler, ks_handler, iter_solver_tol=1e-13)

WARNING! it might be required to pass more Davidson iterations because the defaul 20 might not be enough to converge wave-functions to a given tolerance; this should be done with a new paramter to sirius_find_eigen_states() which passes the number of iterations


The modifications in kcw_nscf can look the following:
```
    !
    ! create k-point set
    ! WARNING: k-points must be provided in fractional coordinates of the reciprocal lattice and
    !          without x2 multiplication for the lsda case
    CALL sirius_create_kset(sctx, num_kpoints, kpoints, wkpoints, .FALSE., ks_handler1)
    !
    ! create ground-state class
    CALL sirius_create_ground_state(ks_handler1, gs_handler1)
    CALL put_density_to_sirius(gs_handler1)
    IF (okpaw) THEN
      CALL put_density_matrix_to_sirius(gs_handler1)
      CALL sirius_generate_density(gs_handler1, paw_only=.TRUE.)
    ENDIF
    CALL sirius_generate_effective_potential(gs_handler1)

    CALL sirius_initialize_subspace(gs_handler1, ks_handler1)
    CALL sirius_find_eigen_states(gs_handler1, ks_handler1, iter_solver_tol=1e-13, iter_solver_steps=100)

! at this point sirius ks_handler1 will store the wave-functions which will have to be extraced to QE
    ```

**Comment by toxa81** [comment]
@gcistaro  I guess `CALL sirius_find_eigen_states(gs_handler1, ks_handler1, iter_solver_tol=1.d-13, iter_solver_steps=100)` requires a small change in API.  We first need to start with sirius side. You can add it to Wannier90 PR, or create a new one

**Comment by gcistaro** [comment]
Hi @toxa81 , 
the branch is already in SIRIUS: https://github.com/electronic-structure/SIRIUS/tree/Adding_number_of_steps

**Comment by toxa81** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
@gcistaro Do you know why h2o Koopman test fails?

**Comment by gcistaro** [comment]
Not really. I need to investigate it a bit further. But it was never working, maybe we can remove it and I try to make it work in a PR?

**Comment by toxa81** [comment]
Interesting. Now h20 koopman's work, and CrI3 fails? Does nscf in HP also usig Sirius? If so, can it be temporay disabled to check that this is the cause of the problem? It is also worth explorig if 200 iterative steps will make wave-functions better.

**Comment by gcistaro** [comment]
Hi @toxa81 !
I have disabled nscf in hp.x, now CrI3 is working. 
Looking at the pseudos, I have noticed that it is using PAW, and it is the only test using HP and PAW. Can this be the thing that breaks nscf?

**Comment by toxa81** [comment]
@gcistaro can we close this PR?

**Comment by gcistaro** [comment]
Yes!

**Pull request closed without merging**
