### PR TITLE
ZGEMM in hp_dnsq

### PR DESCRIPTION
**Pull request by gsavva**
dnsq seems to be a bottleneck in benchmarks with 1Rank-12Threads/rank.
Replacing loops with ZGEMM.
`proj1 = (S_k)^H * PSI_k`
`proj2 = (S_k+q)^H * dPSI_k+q`
`dims: [Npw x NwfU]^H * [Npw x Nbnd] => [NwfU x Npw] * [Npw x Nbnd] => [NwfU x Nbnd]`
Existing `proj1` and `proj2` are of dimensions `[Nbnd x NwfU]`, hence the transpose.

### CODE REVIEW

**Comment by gsavva** [comment]
Similar modifications (loops --> ZGEMM) are implemented in native QE side, in this [PR](https://gitlab.com/QEF/q-e/-/merge_requests/2332), with [these changes](https://gitlab.com/QEF/q-e/-/commit/4fd099634ffa243109000ad122657e32ae28391c).
Some remarks:
- the loop over occupied bands `DO ibnd = 1, nbnd_occ(ikk)` is eliminated.
- the loop over m `DO m = 1, ldim` is eliminated and `ihubst` is modified accordingly
- the loop over atoms and the check `IF (is_hubbard(nt)) THEN` **is kept**.

However, `ihubst` runs over the full 2nd dimension of `proj1` and `proj2`.
Unless I've missed something very fundamental, it seems that the entire loop over (only the Hubbard) atoms can be replaced with 2 ZGEMMs.

That's exactly what I did in this PR and tests are passing !

@timrov could you please have a look on the above modifications?

**Comment by gsavva** [comment]
cscs-run

**Comment by gsavva** [comment]
cscs-ci run

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
@toxa81 shall we merge this PR ?
However, we have the same issue with some CI tests failing randomly, even during the scf step, not HP (specifically, Ni, Ni parallel, and Mn2N2).
For the new test added in this PR `Mn2N2`, I've double-checked that SIRIUS produces the same results as native QE, both locally and on Piz Daint.

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
@toxa81 as weird as it may sound, parallelizing over **only** kpoints for `Mn2N2` causes the test to fail (but it never fails locally or on Daint).
Nevertheless, the test passes when parallelizing over kpoints **and** PW!
The last two trials ([b0d322e](https://github.com/electronic-structure/q-e-sirius/pull/66/commits/b0d322ea4c16a62330c35fc53fa5f542dafefa6f), [99361b0](https://github.com/electronic-structure/q-e-sirius/pull/66/commits/99361b0f0a6c0ac19ae73d0ff01d58e955b73028)) failed because they run out of time (HP finished but processing the timers went over the 30-minutes limit).
Now all tests are green :white_check_mark:
Let me know if you have any comments regarding this PR

**Review by toxa81 — APPROVED** [review]
all good

**Pull request merged**
