### PR TITLE
Fix linear solver for metals

### PR DESCRIPTION
**Pull request by gsavva**
The [PR on SIRIUS side](https://github.com/electronic-structure/SIRIUS/pull/997) should be merged first.
The `sirius_linear_solver` takes one more argument

### CODE REVIEW

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by gsavva** [comment]
the reference U value was obtained from native QE `HP v.7.2`

**Comment by gsavva** [comment]
strange failure of `test LiCoO2` because the scf step did not converge in 100 steps ...

**Comment by gsavva** [comment]
cscs-ci run default

**Comment by toxa81** [comment]
@gsavva Can I merge this RP and you continue to debug CI/CD in another PR? Otherwise ci/cd of sirius breaks due to API chage.

**Comment by gsavva** [comment]
> @gsavva Can I merge this RP and you continue to debug CI/CD in another PR? Otherwise ci/cd of sirius breaks due to API chage.

@toxa81 of course, good to go. I've tested the LR fix locally for many metallic systems and the agreement between native QE HP and q-e-sirius HP is excellent.

**Pull request merged**
