### PR TITLE
LR code: quick performance optimisations

### PR DESCRIPTION
**Pull request by toxa81**
* add timing to qvan2
* add simple omp statements

### CODE REVIEW

**Comment by toxa81** [comment]
@gsavva @gcistaro 
I propose to merge this even when KCW ci/cd tests don't pass. This can be fixed in another PR.

**Comment by gsavva** [comment]
@toxa81 hp.x tests pass so ok from my side.
What was the reason to revert to old CI (https://github.com/electronic-structure/q-e-sirius/pull/43/commits/6330e197a71606fca25e2855c2c93ea43dbfbacc) and reoptimize newdq (https://github.com/electronic-structure/q-e-sirius/pull/43/commits/78cc2b4b0b04ebe4f9807b57c1afa748b7736e7c) ?
Regarding KCW, is it clear why in Si_koopmans the error `Non-existing DFT ground state handler` happen?

**Comment by gcistaro** [comment]
For KCW, the error seems a bit random, each time it runs again it fails at a different step.
For me it is also good to merge it

**Comment by toxa81** [comment]
> @toxa81 hp.x tests pass so ok from my side. What was the reason to revert to old CI ([6330e19](https://github.com/electronic-structure/q-e-sirius/commit/6330e197a71606fca25e2855c2c93ea43dbfbacc)) and reoptimize newdq ([78cc2b4](https://github.com/electronic-structure/q-e-sirius/commit/78cc2b4b0b04ebe4f9807b57c1afa748b7736e7c)) ? Regarding KCW, is it clear why in Si_koopmans the error `Non-existing DFT ground state handler` happen?

There was a small bug introduced by me: dot_product(x,y) is cojg(x)*y, not x*y as I implemented initially. Now this is fixed as ci/cd shows. 

Regarding error `Non-existing DFT ground state handler` - somthing is wrong for sure

**Comment by gcistaro** [comment]
@toxa81 I have noticed that I did not merge my interface between kcw and SIRIUS, maybe this error is coming from the fact the LR in QE calls SIRIUS functions? Should I merge my changes in KCW here?

**Comment by toxa81** [comment]
> @toxa81 I have noticed that I did not merge my interface between kcw and SIRIUS, maybe this error is coming from the fact the LR in QE calls SIRIUS functions? Should I merge my changes in KCW here?

true! The KCW interface will be tested in its own PR. So let's merge it to enable ci/cd

**Pull request merged**
