### PR TITLE
Build for Cray (GCC + FFTW + libsci)

### PR DESCRIPTION
**Pull request by toxa81**
This should produce a valid build
```
git clone --recursive -b fix/cmake-build-cray https://github.com/electronic-structure/q-e-sirius.git
mkdir q-e-sirius/build && cd ./q-e-sirius/build
module swap PrgEnv-cray PrgEnv-gnu
module load cray-fftw
module load daint-gpu
module load CMake
cmake .. -DQE_ENABLE_OPENMP=1 -DBLA_VENDOR=Cray -DFFTW3_INCLUDE_DIRS=$FFTW_INC
```
This should produce a valid configuration, but there are several problems:
1) FFTW is found not in a clean way
```
-- Could NOT find VendorFFTW (missing: VendorFFTW_LIBRARIES VendorFFTW_INCLUDE_DIRS VendorFFTW_ID)
-- No vendor FFTW found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Found FFTW3: /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3.a;/opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3_omp.a
```
2) Static version of Cray libsci is found
```
-- Found LAPACK: /opt/cray/pe/libsci/20.06.1/GNU/8.1/x86_64/lib/libsci_gnu_mpi_mp.a
```
This will produce an error at the linking stage due to the unresolved symbols in libsci_gnu_mpi_mp.a. Dynamical libray libsci_gnu_mpi_mp.so should be used. Also, depending on the `QE_ENABLE_OPENMP` and 'QE_ENABLE_MPI' flags different version of  libsci_gnu_ should be picked.

### CODE REVIEW

**Comment by toxa81** [comment]
@simonpintarelli @AdhocMan can you please help me with this issue. I want to build with GNU+libsci

**Comment by simonpintarelli** [comment]
I'll take care of it.

**Comment by AdhocMan** [comment]
1.  What do you mean by FFTW is not found in a clean way? Looks to me like it first checks if FFTW is provided by a vendor library like MKL and if not, looks for an FFTW3 installtation. The cray-fftw module provides standard fftw3 libraries, which are found correctly.
2. A general workaround to force CMake to only find shared libraries is to set `CMAKE_FIND_LIBRARY_SUFFIXES` to `".so"`. Either through setting it globally from command line or by wrapping the find call for libsci. You would have to clear the cache beforehand, otherwise CMake won't look for the library again.
But ideally, the find module should also find other required dependencies, such that one can also link against the static version.

**Comment by AdhocMan** [comment]
Just noticed, the message for the static cray library is from `find_package(LAPACK)` and not from the custom module. In that case, using `-DBLA_STATIC=OFF` may help.

**Comment by simonpintarelli** [comment]
It compiles and links when setting `CRAYPE_LINK_TYPE=dynamic`. Shall we add a check to cmake and throw an error if it's not set in the environment?

**Comment by toxa81** [comment]
>     1. What do you mean by FFTW is not found in a clean way? Looks to me like it first checks if FFTW is provided by a vendor library like MKL and if not, looks for an FFTW3 installtation. The cray-fftw module provides standard fftw3 libraries, which are found correctly.

I was concerned about this lines
https://github.com/electronic-structure/q-e-sirius/blob/fix/cmake-build-cray/cmake/FindFFTW3.cmake#L45-L52
Do you think that they are correct?

**Comment by toxa81** [comment]
> It compiles and links when setting `CRAYPE_LINK_TYPE=dynamic`. Shall we add a check to cmake and throw an error if it's not set in the environment?

As a first workaround, yes. Let me check if I can build it now.

**Comment by simonpintarelli** [comment]
> I was concerned about this lines
> https://github.com/electronic-structure/q-e-sirius/blob/fix/cmake-build-cray/cmake/FindFFTW3.cmake#L45-L52
> Do you think that they are correct?

This looks good to me.

**Comment by simonpintarelli** [comment]
```
[ 15%] Built target qe_kssolver_davidsonrci
/usr/bin/ld: /opt/cray/pe/libsci/20.06.1/GNU/8.1/x86_64/lib/libsci_gnu_82_mp.a(crayblas_util.o): in function `__allocBlasMemPool.localalias.0':
crayblas_util.c:(.text+0x2ee): undefined reference to `hugetlbfs_find_path_for_size'
/usr/bin/ld: crayblas_util.c:(.text+0x301): undefined reference to `hugetlbfs_unlinked_fd_for_size'
```

I'm getting the above error for static linking. Does someone know where `hugetlbfs_unlinked_fd_for_size` is supposed to be defined?

**Comment by toxa81** [comment]
It's in the same folder as libsci...a. This is exactly my problem: how to tell it to use .so?

**Comment by toxa81** [comment]
`CRAYPE_LINK_TYPE=dynamic make -j12` works for me
```
ldd pw.x
	linux-vdso.so.1 (0x00007ffeb3daf000)
	/apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libxalt_init.so (0x00002aba947e2000)
	libfftw3.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3.so.mpi31.3 (0x00002aba949f8000)
	libfftw3_omp.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3_omp.so.mpi31.3 (0x00002aba9565c000)
	libfftw3f_omp.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3f_omp.so.mpi31.3 (0x00002aba95863000)
	libsci_gnu_82_mpi_mp.so.5 => /opt/cray/pe/libsci/20.06.1/GNU/8.1/x86_64/lib/libsci_gnu_82_mpi_mp.so.5 (0x00002aba95a6a000)
	libsci_gnu_82_mp.so.5 => /opt/cray/pe/libsci/20.06.1/GNU/8.1/x86_64/lib/libsci_gnu_82_mp.so.5 (0x00002aba961fa000)
	libgomp.so.1 => /opt/gcc/8.3.0/snos/lib64/libgomp.so.1 (0x00002aba9ba05000)
	libmvec.so.1 => /lib64/libmvec.so.1 (0x00002aba9bc34000)
	libAtpSigHandler.so.1 => /opt/cray/pe/atp/3.7.4/lib/libAtpSigHandler.so.1 (0x00002aba9be5e000)
	librca.so.0 => /opt/cray/rca/2.2.20-7.0.2.1_2.27__g8e3fb5b.ari/lib64/librca.so.0 (0x00002aba9c09c000)
	libfftw3_mpi.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3_mpi.so.mpi31.3 (0x00002aba9c2a0000)
	libfftw3_threads.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3_threads.so.mpi31.3 (0x00002aba9c4b6000)
	libfftw3f_mpi.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3f_mpi.so.mpi31.3 (0x00002aba9c6bd000)
	libfftw3f_threads.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3f_threads.so.mpi31.3 (0x00002aba9c8d3000)
	libfftw3f.so.mpi31.3 => /opt/cray/pe/fftw/3.3.8.7/haswell/lib/libfftw3f.so.mpi31.3 (0x00002aba9cada000)
	libmpich_gnu_82.so.3 => /opt/cray/pe/mpt/7.7.15/gni/mpich-gnu/8.2/lib/libmpich_gnu_82.so.3 (0x00002aba9d025000)
	libgfortran.so.5 => /opt/gcc/8.3.0/snos/lib64/libgfortran.so.5 (0x00002aba9d5e7000)
	libpthread.so.0 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libpthread.so.0 (0x00002aba9da56000)
	libm.so.6 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libm.so.6 (0x00002aba9dc75000)
	libgcc_s.so.1 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libgcc_s.so.1 (0x00002aba9dfad000)
	libquadmath.so.0 => /opt/gcc/8.3.0/snos/lib64/libquadmath.so.0 (0x00002aba9e1c5000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aba9e405000)
	libdl.so.2 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libdl.so.2 (0x00002aba9e7c0000)
	libhugetlbfs.so => /usr/lib64/libhugetlbfs.so (0x00002aba9e9c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aba945ba000)
	librt.so.1 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/librt.so.1 (0x00002aba9ebfc000)
	libxpmem.so.0 => /opt/cray/xpmem/2.2.20-7.0.2.1_2.21__g87eb960.ari/lib64/libxpmem.so.0 (0x00002aba9ee04000)
	libugni.so.0 => /opt/cray/ugni/6.0.14.0-7.0.2.1_3.21__ge78e5b0.ari/lib64/libugni.so.0 (0x00002aba9f007000)
	libudreg.so.0 => /opt/cray/udreg/2.3.2-7.0.2.1_2.21__g8175d3d.ari/lib64/libudreg.so.0 (0x00002aba9f28b000)
	libpmi.so.0 => /opt/cray/pe/pmi/5.0.16/lib64/libpmi.so.0 (0x00002aba9f495000)
	libz.so.1 => /apps/daint/UES/xalt/xalt2/software/xalt/2.8.10/lib64/libz.so.1 (0x00002aba9f6de000)
	```

**Comment by simonpintarelli** [comment]
https://github.com/Kitware/CMake/blob/master/Modules/Compiler/CrayPrgEnv.cmake#L60

Isn't one supposed to set `CRAYPE_LINK_TYPE=dynamic` when one wants to link against dynamic libraries?

**Comment by AdhocMan** [comment]
I was just looking at the same file and I think we have Cray PE 2.7.0 on daint, so it should default to dynamic.

**Comment by simonpintarelli** [comment]
Strange, it is a bug in the cray environment then? When setting `CRAYPE_LINK_TYPE=static` static linking works for me (e.g. vs not setting CRAYPE_LINK_TYPE, in this case static libraries are selected, but linking fails on symbols  from `hugetlbfs`)

**Pull request closed without merging**
